/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppGrafica;

/**
 *
 * @author gordito
 */
import Clases.Correo;
import Clases.Manejadora;
import Clases.Stack;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


public class frmCorreo extends javax.swing.JFrame {

    /**
     * Creates new form frmCorreo
     */
    Stack<Correo> correos = new Stack();
    Stack<Correo> leidos = new Stack();
    Stack<Correo> urgente = new Stack();
    Stack<Correo> revisar = new Stack();
    Manejadora mane = new Manejadora();
    
    
    
    public frmCorreo() {
        initComponents();
        RescataCorreos();
        this.setSize(600,600);
        this.setLocationRelativeTo(null);
        
    }
    
    public void RescataCorreos()
    {
        try{
            FileReader f = new FileReader("entrada.txt");
            Scanner sf =  new Scanner(f);
            while(sf.hasNextLine()){
                String linea = sf.nextLine();                
                Correo cor = new Correo(linea);
                correos.push(cor);
            }
            sf.close();
            f.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Error al abrir archivo entrada.txt");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGuardar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBandeja = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaRevisar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaUrgente = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnLeer = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        rdbUrgente = new javax.swing.JRadioButton();
        rdbRevisar = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblLeido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Bandeja de Entrada");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 170, 17);

        txtAreaBandeja.setColumns(20);
        txtAreaBandeja.setRows(5);
        jScrollPane1.setViewportView(txtAreaBandeja);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 580, 180);

        jLabel2.setText("Revisar ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 230, 90, 17);

        txtAreaRevisar.setColumns(20);
        txtAreaRevisar.setRows(5);
        jScrollPane2.setViewportView(txtAreaRevisar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 260, 580, 30);

        jLabel3.setText("Urgente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 300, 100, 17);

        txtAreaUrgente.setColumns(20);
        txtAreaUrgente.setRows(5);
        jScrollPane3.setViewportView(txtAreaUrgente);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 320, 580, 30);

        jLabel4.setText("Leído");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 360, 70, 17);

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeer);
        btnLeer.setBounds(10, 430, 70, 29);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(10, 470, 100, 29);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(482, 420, 90, 29);

        panelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btgGuardar.add(rdbUrgente);
        rdbUrgente.setSelected(true);
        rdbUrgente.setText("Urgente");

        btgGuardar.add(rdbRevisar);
        rdbRevisar.setText("Revisar");

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbUrgente)
                    .addComponent(rdbRevisar))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbUrgente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbRevisar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(panelGuardar);
        panelGuardar.setBounds(160, 430, 120, 130);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLeido, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLeido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 380, 580, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
       
        lblLeido.setText(null);
        lblLeido.setText(mane.LeerCorreo(correos));
        
        txtAreaBandeja.setText(null);
        txtAreaBandeja.append(mane.LeerStack(correos));
        txtAreaBandeja.select(1, 1);

    }//GEN-LAST:event_btnLeerActionPerformed

    
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        txtAreaBandeja.setText(null);
        txtAreaBandeja.append(mane.LeerStack(correos));
        txtAreaBandeja.select(1, 1);
        
        txtAreaUrgente.setText(null);
        txtAreaUrgente.append(mane.LeerStack(urgente));
        txtAreaUrgente.select(1, 1);
        
        txtAreaRevisar.setText(null);
        txtAreaRevisar.append(mane.LeerStack(revisar));
        txtAreaRevisar.select(1, 1);
                       
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
          if (rdbUrgente.isSelected())
          {
              txtAreaUrgente.setText(null);
              txtAreaUrgente.append(mane.Traspasa(urgente, lblLeido.getText()));
              txtAreaUrgente.select(1, 1);
           }
              
          if (rdbRevisar.isSelected())
          {
              txtAreaRevisar.setText(null);
              txtAreaRevisar.append(mane.Traspasa(revisar, lblLeido.getText()));
              txtAreaRevisar.select(1, 1);
          }

        lblLeido.setText(null);

    }//GEN-LAST:event_btnGuardarActionPerformed

      
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup btgGuardar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLeido;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JRadioButton rdbRevisar;
    private javax.swing.JRadioButton rdbUrgente;
    private javax.swing.JTextArea txtAreaBandeja;
    private javax.swing.JTextArea txtAreaRevisar;
    private javax.swing.JTextArea txtAreaUrgente;
    // End of variables declaration//GEN-END:variables
}
